apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codesnap-app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - 3.64.180.31.sslip.io
      secretName: codesnap-tls-prod-v1 # The original working secret name
  rules:
    - host: 3.64.180.31.sslip.io
      http:
        paths:
          # Main Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codesnap-fe
                port:
                  number: 80
          # Keycloak Backend (Subpath)
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          # Required for Keycloak Login UI Assets
          - path: /resources
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          # Required for Login Protocols
          - path: /realms
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
