apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codesnap-app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - 3.64.180.31.sslip.io
      secretName: codesnap-tls-prod-v1
  rules:
    - host: 3.64.180.31.sslip.io
      http:
        paths:
          - path: /exercises
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000

          - path: /attempts
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000

          - path: /users
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000

          - path: /code
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000

          - path: /ai
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8000

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - path: /resources
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - path: /realms
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - path: /js
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codesnap-fe
                port:
                  number: 80
