apiVersion: v1
kind: Service
metadata:
  name: codesnap-fe
  labels:
    app: codesnap-fe
spec:
  type: LoadBalancer
  selector:
    app: codesnap-fe
  ports:
    - port: 5173
      targetPort: 80
      protocol: TCP
