apiVersion: v1
kind: Service
metadata:
  name: codesnap-fe
  labels:
    app: codesnap-fe
spec:
  type: ClusterIP
  selector:
    app: codesnap-fe
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
